import {initializeApp} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import {getAuth,GoogleAuthProvider,signInWithPopup,onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";

const firebaseConfig={apiKey:"AIzaSyA76f8G8L-GDKNuMKbtaORnuDfagRA3zY8",authDomain:"gst-bill-maker-d7956.firebaseapp.com",projectId:"gst-bill-maker-d7956",storageBucket:"gst-bill-maker-d7956.firebasestorage.app",messagingSenderId:"564339961180",appId:"1:564339961180:web:0e9ff371695d0beeade599"};
const auth=getAuth(initializeApp(firebaseConfig)),provider=new GoogleAuthProvider();
const $=id=>document.getElementById(id), money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
let items=[{name:"",hsn:"",qty:1,rate:0,gst:18}],logo="";

function today(){let d=new Date();d=new Date(d-d.getTimezoneOffset()*60000);$("invoiceDate").value=d.toISOString().slice(0,10)} today();
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function render(){
$("itemsBody").innerHTML=items.map((x,i)=>`<tr class="border-b">
<td class="p-2">${i+1}</td><td class="p-2"><input class="field" data-i="${i}" data-k="name" value="${esc(x.name)}" placeholder="Item"></td>
<td class="p-2"><input class="field" data-i="${i}" data-k="hsn" value="${esc(x.hsn)}" placeholder="HSN/SAC *" required></td>
<td class="p-2"><input type="number" class="field" data-i="${i}" data-k="qty" value="${x.qty}" min="0" step=".01"></td>
<td class="p-2"><input type="number" class="field" data-i="${i}" data-k="rate" value="${x.rate}" min="0" step=".01"></td>
<td class="p-2"><select class="field" data-i="${i}" data-k="gst">${[0,5,12,18,28].map(g=>`<option value="${g}" ${+x.gst===g?"selected":""}>${g}%</option>`).join("")}</select></td>
<td class="p-2 pt-5 font-bold">${money(x.qty*x.rate)}</td><td><button data-del="${i}" class="text-red-600 text-xl">×</button></td></tr>`).join("");calc()}
$("itemsBody").oninput=e=>{let t=e.target;if(!t.dataset.i)return;let i=+t.dataset.i,k=t.dataset.k;items[i][k]=["name","hsn"].includes(k)?t.value:+t.value;calc()};
$("itemsBody").onclick=e=>{let b=e.target.closest("[data-del]");if(!b)return;if(items.length>1)items.splice(+b.dataset.del,1);else items=[{name:"",hsn:"",qty:1,rate:0,gst:18}];render()};
$("addItemBtn").onclick=()=>{items.push({name:"",hsn:"",qty:1,rate:0,gst:18});render()};render();

function calc(){
let taxable=0,cgst=0,sgst=0,igst=0,intra=$("sellerState").value.trim().toLowerCase()&&$("buyerState").value.trim().toLowerCase()&&$("sellerState").value.trim().toLowerCase()===$("buyerState").value.trim().toLowerCase();
items.forEach(x=>{let b=(+x.qty||0)*(+x.rate||0),t=b*(+x.gst||0)/100;taxable+=b;if(intra){cgst+=t/2;sgst+=t/2}else igst+=t});
$("summaryTaxable").textContent=money(taxable);$("summaryCGST").textContent=money(cgst);$("summarySGST").textContent=money(sgst);$("summaryIGST").textContent=money(igst);$("summaryGrand").textContent=money(taxable+cgst+sgst+igst);$("summaryMode").textContent=intra?"Intra-state: CGST + SGST":"Inter-state: IGST";return{taxable,cgst,sgst,igst,grand:taxable+cgst+sgst+igst,intra}}
document.querySelectorAll("input,textarea").forEach(x=>x.addEventListener("input",calc));
$("logoInput").onchange=()=>{let f=$("logoInput").files[0];if(!f)return;let r=new FileReader();r.onload=()=>logo=r.result;r.readAsDataURL(f)};

function data(){return{seller:{name:$("sellerName").value,address:$("sellerAddress").value,gstin:$("sellerGSTIN").value,state:$("sellerState").value},buyer:{name:$("buyerName").value,address:$("buyerAddress").value,gstin:$("buyerGSTIN").value,state:$("buyerState").value},no:$("invoiceNumber").value,date:$("invoiceDate").value,place:$("placeSupply").value,notes:$("notes").value,terms:$("terms").value,items,logo}}
function valid(){let d=data();for(let [id,n] of [["sellerName","Seller name"],["sellerAddress","Seller address"],["sellerGSTIN","Seller GSTIN"],["sellerState","Seller state"],["buyerName","Buyer name"],["buyerAddress","Buyer address"],["buyerGSTIN","Buyer GSTIN"],["buyerState","Buyer state"],["invoiceNumber","Invoice number"],["invoiceDate","Invoice date"]])if(!$(id).value.trim()){alert("Please enter "+n);$(id).focus();return false}if(items.some(x=>!x.hsn.trim())){alert("HSN/SAC is required for every item.");return false}if(items.some(x=>!x.name.trim())){alert("Item name is required for every item.");return false}return true}
function words(n){n=Math.round(n);if(!n)return"Zero Rupees Only";let o=["","One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten","Eleven","Twelve","Thirteen","Fourteen","Fifteen","Sixteen","Seventeen","Eighteen","Nineteen"],t=["","","Twenty","Thirty","Forty","Fifty","Sixty","Seventy","Eighty","Ninety"],tw=n=>n<20?o[n]:t[Math.floor(n/10)]+(n%10?" "+o[n%10]:""),th=n=>n>=100?o[Math.floor(n/100)]+" Hundred"+(n%100?" "+tw(n%100):""):tw(n);let s="";if(n>=1e7){s+=th(Math.floor(n/1e7))+" Crore ";n%=1e7}if(n>=1e5){s+=th(Math.floor(n/1e5))+" Lakh ";n%=1e5}if(n>=1e3){s+=th(Math.floor(n/1e3))+" Thousand ";n%=1e3}return(s+(n?th(n):"")).trim()+" Rupees Only"}
function invoice(){
let d=data(),c=calc(),rows=d.items.map((x,i)=>{let b=x.qty*x.rate,t=b*x.gst/100;return`<tr><td>${i+1}</td><td><b>${esc(x.name)}</b></td><td>${esc(x.hsn)}</td><td class="r">${x.qty}</td><td class="r">${money(x.rate)}</td><td class="r">${money(b)}</td><td class="r">${x.gst}%</td><td class="r">${money(t)}</td><td class="r"><b>${money(b+t)}</b></td></tr>`}).join("");
let logoHtml=d.logo?`<img class="logo" src="${d.logo}">`:`<div class="mark">GB</div>`, tax=c.intra?`<tr><td>CGST</td><td>${money(c.cgst)}</td></tr><tr><td>SGST</td><td>${money(c.sgst)}</td></tr>`:`<tr><td>IGST</td><td>${money(c.igst)}</td></tr>`;
return`<style>
.pdf{font-family:Arial,sans-serif;color:#172033;padding:13mm;font-size:9px}.head{background:#111827;color:#fff;border-radius:12px;padding:20px;display:flex;justify-content:space-between}.brand{display:flex;gap:11px;align-items:center}.mark,.logo{width:43px;height:43px;border-radius:9px}.mark{background:#2563eb;color:#fff;display:grid;place-items:center;font-weight:900}.logo{object-fit:contain;background:#fff}.company{font-size:17px;font-weight:900}.muted{color:#cbd5e1}.title{font-size:21px;font-weight:900;text-align:right}.meta{font-size:8px;color:#cbd5e1;margin-top:4px}.cards{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:12px}.card{background:#f8fafc;border:1px solid #e2e8f0;border-radius:9px;padding:11px}.blue{background:#eff6ff}.lbl{font-size:7px;color:#64748b;font-weight:800;text-transform:uppercase;letter-spacing:.7px}.nm{font-size:11px;font-weight:900;margin:4px 0}.info{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-top:9px}.info .card{padding:9px}table{width:100%;border-collapse:collapse}.items{margin-top:13px}.items th{background:#172033;color:white;padding:7px;text-align:left;font-size:7px}.items td{padding:7px;border-bottom:1px solid #e5e7eb}.items tbody tr:nth-child(even){background:#f8fafc}.r{text-align:right}.bottom{display:grid;grid-template-columns:1.25fr .75fr;gap:10px;margin-top:12px}.notes,.totals{border:1px solid #e2e8f0;border-radius:9px;padding:11px}.totals{background:#f8fafc}.totals td{padding:4px}.grand{margin-top:7px;background:#111827;color:#fff;border-radius:8px;padding:10px;display:flex;justify-content:space-between;align-items:center}.grand b{font-size:16px}.words{margin-top:10px;background:#eff6ff;border:1px solid #dbeafe;border-radius:9px;padding:10px}.words b{font-size:11px}.foot{border-top:1px solid #e2e8f0;margin-top:15px;padding-top:8px;color:#64748b;font-size:7px;display:flex;justify-content:space-between}
</style><div class="pdf"><div class="head"><div class="brand">${logoHtml}<div><div class="company">${esc(d.seller.name)}</div><div class="muted">${esc(d.seller.address).replace(/\n/g,"<br>")}</div><div class="meta">GSTIN: ${esc(d.seller.gstin)} · ${esc(d.seller.state)}</div></div></div><div><div class="title">TAX INVOICE</div><div class="meta">Professional GST Invoice</div></div></div>
<div class="cards"><div class="card"><div class="lbl">Bill From</div><div class="nm">${esc(d.seller.name)}</div><div>${esc(d.seller.address).replace(/\n/g,"<br>")}</div><div><b>GSTIN:</b> ${esc(d.seller.gstin)}</div></div><div class="card blue"><div class="lbl">Bill To</div><div class="nm">${esc(d.buyer.name)}</div><div>${esc(d.buyer.address).replace(/\n/g,"<br>")}</div><div><b>GSTIN:</b> ${esc(d.buyer.gstin)}</div></div></div>
<div class="info"><div class="card"><div class="lbl">Invoice Number</div><b>${esc(d.no)}</b></div><div class="card"><div class="lbl">Invoice Date</div><b>${d.date.split("-").reverse().join("/")}</b></div><div class="card"><div class="lbl">Place of Supply</div><b>${esc(d.place||d.buyer.state)}</b></div></div>
<table class="items"><thead><tr><th>#</th><th>Item / Service</th><th>HSN/SAC</th><th>Qty</th><th>Rate</th><th>Taxable</th><th>GST</th><th>Tax</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table>
<div class="bottom"><div class="notes"><b>Notes / Payment Terms</b><p>${esc(d.notes||"—").replace(/\n/g,"<br>")}</p><b>Terms & Conditions</b><p>${esc(d.terms||"—").replace(/\n/g,"<br>")}</p></div><div class="totals"><table>${tax}</table><div class="grand"><span>GRAND TOTAL</span><b>${money(c.grand)}</b></div></div></div>
<div class="words"><div class="lbl">AMOUNT IN WORDS</div><b>${words(c.grand)}</b></div><div class="foot"><span>Generated with GST Bill Maker</span><span>Electronic invoice</span></div></div>`}
function show(){if(!valid())return;$("invoicePreview").innerHTML=invoice();$("previewModal").classList.remove("hidden")}
async function pdf(){if(!valid())return;$("invoicePreview").innerHTML=invoice();if(!window.html2pdf)await new Promise((res,rej)=>{let s=document.createElement("script");s.src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js";s.onload=res;s.onerror=rej;document.head.appendChild(s)});let name=($("invoiceNumber").value||"GST-Invoice").replace(/[^a-z0-9_-]/gi,"_");await html2pdf().set({margin:0,filename:name+".pdf",image:{type:"jpeg",quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:"#fff"},jsPDF:{unit:"mm",format:"a4",orientation:"portrait"}}).from($("invoicePreview").querySelector(".pdf")).save()}
$("previewBtn").onclick=show;$("downloadBtn").onclick=pdf;$("previewDownloadBtn").onclick=pdf;$("closePreviewBtn").onclick=()=>$("previewModal").classList.add("hidden");
$("googleLoginBtn").onclick=async()=>{try{await signInWithPopup(auth,provider)}catch(e){$("loginError").textContent=e.message;$("loginError").classList.remove("hidden")}};
$("logoutBtn").onclick=()=>signOut(auth);onAuthStateChanged(auth,u=>{if(u){$("loginPage").classList.add("hidden");$("appPage").classList.remove("hidden");$("userName").textContent=u.displayName||u.email||""}else{$("appPage").classList.add("hidden");$("loginPage").classList.remove("hidden")}});

